### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by extrastu** [electron-modules/graceful-updater#34]
![image](https://user-images.githubusercontent.com/19451694/229670951-75bb5e3d-724a-40bf-ba65-a4f254afd15c.png)
错误如上图，请问webpack 需要怎么配置呢

**Comment by zlyi** [comment]
你好，看提示是你工程里对不支持 ES6 Optional chanining，建议检查 Babel 和 webpack 相关配置。
如果想验证完整功能，可以跑一下 sample 工程：https://github.com/electron-modules/electron-modules-sample。
